export const LINK_COMMUNITY = 'https://visualqa.org/'
export const LINK_DOCUMENTATION = 'https://visualqa.org/challenge.html'
export const VISUAL_QUESTION_ANSWERING = 'Visual Question Answering'
export const COMMUNITY = 'Community' 
export const DOCUMENTATION = 'Documentation'